name: Pipeline CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setut JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven
          restore-keys: ${{ runner.os }}-maven

      - name: Build with maven
        run: mvn clean package

      - name: Copy files via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_ID}}
          username: ${{ secrets.GITHUB_TOKEN}}
          key: ${{secrets.GITHUB_TOKEN}}
          source: "target/*.jar,docker-compose.yml,Dockerfile"
          target: /opt/techstore
          strip_components: 0

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_ID}}
          username: ${{ secrets.GITHUB_TOKEN}}
          key: ${{secrets.GITHUB_TOKEN}}
          script: |
            cd  /opt/techstore
            docker-compose down || true
            docker-compose pull
            docker-compose up --build -d
            docker image prune -f
            docker ps

